// <auto-generated />
using AlzaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AlzaApi.Migrations
{
    [DbContext(typeof(AlzaContext))]
    [Migration("20201029183723_SeedInitData")]
    partial class SeedInitData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AlzaApi.Models.v1_0.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Sleek Granite",
                            ImgUri = "6d2322ba-2001-4fc4-ba4f-7c13606a047b",
                            Name = "Pants",
                            Price = 63.87m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sleek Granite",
                            ImgUri = "81facd31-4038-4daa-abb8-5f5e903978c4",
                            Name = "Pants",
                            Price = 79.16m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Ergonomic Wooden",
                            ImgUri = "4af08ab9-dcf4-4d83-b66b-6ea1c74cf879",
                            Name = "Computer",
                            Price = 66.03m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Small Steel",
                            ImgUri = "86fbdf37-789a-48ac-bd14-6bdc6570f62e",
                            Name = "Car",
                            Price = 48.02m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Small Concrete",
                            ImgUri = "7ea634ec-1c92-4f6f-9982-2ce02395ff66",
                            Name = "Car",
                            Price = 57.66m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Small Plastic",
                            ImgUri = "29862d78-e3e6-4aaa-bc48-16f1178dcb8d",
                            Name = "Pants",
                            Price = 16.86m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Ergonomic Concrete",
                            ImgUri = "13910f49-6000-4534-8c63-37b25c5d8f60",
                            Name = "Car",
                            Price = 56.65m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Sleek Plastic",
                            ImgUri = "d7309147-c19d-40f3-a77f-11913b1a6071",
                            Name = "Pants",
                            Price = 86.67m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Small Plastic",
                            ImgUri = "4263fccf-fd6d-4a28-b59c-5d27c0d7708b",
                            Name = "Pants",
                            Price = 19.18m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Smart Concrete",
                            ImgUri = "50688757-79ca-44f3-9b4c-205cbdfc6fe8",
                            Name = "Shoes",
                            Price = 28.11m
                        },
                        new
                        {
                            Id = 11,
                            Description = "Sleek Concrete",
                            ImgUri = "ea7060da-8c70-4d91-bc21-f7e7f2b9bdd0",
                            Name = "Chair",
                            Price = 24.07m
                        },
                        new
                        {
                            Id = 12,
                            Description = "Small Steel",
                            ImgUri = "43d71952-8070-45fb-b4f6-8af7a6b4b8c0",
                            Name = "Car",
                            Price = 59.46m
                        },
                        new
                        {
                            Id = 13,
                            Description = "Rustic Steel",
                            ImgUri = "af9ef61e-90a9-4c42-b303-7c35e21e3c6e",
                            Name = "Shoes",
                            Price = 71.4m
                        },
                        new
                        {
                            Id = 14,
                            Description = "Smart Plastic",
                            ImgUri = "749e7807-b6c7-40d3-9410-c21634c29ef3",
                            Name = "Car",
                            Price = 36.47m
                        },
                        new
                        {
                            Id = 15,
                            Description = "Smart Steel",
                            ImgUri = "0d976393-7241-4015-b02b-0a68fe690018",
                            Name = "Pants",
                            Price = 12.41m
                        },
                        new
                        {
                            Id = 16,
                            Description = "Ergonomic Concrete",
                            ImgUri = "01758f9c-b8ce-4b18-8d18-bb4603aab54c",
                            Name = "Computer",
                            Price = 50.71m
                        },
                        new
                        {
                            Id = 17,
                            Description = "Rustic Wooden",
                            ImgUri = "9e900702-5025-4557-a3ba-d62625c6d5e7",
                            Name = "Shoes",
                            Price = 55.87m
                        },
                        new
                        {
                            Id = 18,
                            Description = "Small Steel",
                            ImgUri = "24d3d921-02ca-4c90-bd34-df097ded40cb",
                            Name = "Computer",
                            Price = 48.23m
                        },
                        new
                        {
                            Id = 19,
                            Description = "Ergonomic Concrete",
                            ImgUri = "d31270e7-4ab3-46ff-b4e7-81e2038b3796",
                            Name = "Shoes",
                            Price = 58.36m
                        },
                        new
                        {
                            Id = 20,
                            Description = "Rustic Plastic",
                            ImgUri = "26b664db-339c-42da-84c1-1afad5278b83",
                            Name = "Car",
                            Price = 56.24m
                        },
                        new
                        {
                            Id = 21,
                            Description = "Rustic Granite",
                            ImgUri = "1c52e593-bc8e-4fde-b507-83a18078d0ac",
                            Name = "Computer",
                            Price = 34.38m
                        },
                        new
                        {
                            Id = 22,
                            Description = "Rustic Wooden",
                            ImgUri = "db51a4ab-fa3f-41fb-99ff-63438596d414",
                            Name = "Computer",
                            Price = 79.33m
                        },
                        new
                        {
                            Id = 23,
                            Description = "Small Granite",
                            ImgUri = "223f8c00-1af4-4100-8d76-95c495f29ca2",
                            Name = "Computer",
                            Price = 38.8m
                        },
                        new
                        {
                            Id = 24,
                            Description = "Small Plastic",
                            ImgUri = "28690675-d8bd-4a5e-a9fb-87fe877d8c3b",
                            Name = "Computer",
                            Price = 54.95m
                        },
                        new
                        {
                            Id = 25,
                            Description = "Smart Plastic",
                            ImgUri = "fc2df5a9-7a50-4cdc-9e3d-e74488cbbd15",
                            Name = "Shoes",
                            Price = 30.34m
                        },
                        new
                        {
                            Id = 26,
                            Description = "Smart Concrete",
                            ImgUri = "d25430c3-3073-415f-8902-244643ca7df1",
                            Name = "Chair",
                            Price = 80.03m
                        },
                        new
                        {
                            Id = 27,
                            Description = "Small Plastic",
                            ImgUri = "7438522f-ad7c-4193-b4cb-d81f291f0be0",
                            Name = "Pants",
                            Price = 45.49m
                        },
                        new
                        {
                            Id = 28,
                            Description = "Rustic Steel",
                            ImgUri = "4ce868c6-d10b-48cc-b7a4-c37dcd7a79a6",
                            Name = "Chair",
                            Price = 24.55m
                        },
                        new
                        {
                            Id = 29,
                            Description = "Smart Steel",
                            ImgUri = "00247789-2615-43f6-be60-c7f1f6b186c2",
                            Name = "Computer",
                            Price = 88.63m
                        },
                        new
                        {
                            Id = 30,
                            Description = "Small Granite",
                            ImgUri = "c08d1c2f-c473-44e7-81d0-c2c5e4777df8",
                            Name = "Chair",
                            Price = 38.75m
                        },
                        new
                        {
                            Id = 31,
                            Description = "Smart Steel",
                            ImgUri = "26cde609-ec4e-4993-9b0b-ab3d45c10e7e",
                            Name = "Chair",
                            Price = 26.62m
                        },
                        new
                        {
                            Id = 32,
                            Description = "Rustic Wooden",
                            ImgUri = "545263da-1db7-40ae-92dd-efa06fe756d9",
                            Name = "Computer",
                            Price = 36.58m
                        },
                        new
                        {
                            Id = 33,
                            Description = "Rustic Granite",
                            ImgUri = "4fac1530-fe76-4b8f-8cfd-042e7d632511",
                            Name = "Computer",
                            Price = 57.38m
                        },
                        new
                        {
                            Id = 34,
                            Description = "Smart Concrete",
                            ImgUri = "dfde13b3-ea6e-4e45-aaac-2418919f8464",
                            Name = "Shoes",
                            Price = 85.65m
                        },
                        new
                        {
                            Id = 35,
                            Description = "Ergonomic Steel",
                            ImgUri = "a2c121b0-d965-490b-b6b8-186bd5a4fa7e",
                            Name = "Pants",
                            Price = 80.98m
                        },
                        new
                        {
                            Id = 36,
                            Description = "Ergonomic Wooden",
                            ImgUri = "66efa14f-e33a-41e2-bef3-d910115a2272",
                            Name = "Pants",
                            Price = 66.28m
                        },
                        new
                        {
                            Id = 37,
                            Description = "Ergonomic Concrete",
                            ImgUri = "481b91f9-258e-4542-867f-497dca5db47e",
                            Name = "Shoes",
                            Price = 12.62m
                        },
                        new
                        {
                            Id = 38,
                            Description = "Rustic Concrete",
                            ImgUri = "d7ae40c7-6817-496d-801d-0322960c69fe",
                            Name = "Shoes",
                            Price = 81.09m
                        },
                        new
                        {
                            Id = 39,
                            Description = "Rustic Granite",
                            ImgUri = "7b5c2ec5-4697-4249-87c2-c676bccf0ccb",
                            Name = "Chair",
                            Price = 68.2m
                        },
                        new
                        {
                            Id = 40,
                            Description = "Small Wooden",
                            ImgUri = "24f7d5aa-5650-4c47-8810-e71138d0b640",
                            Name = "Chair",
                            Price = 53.63m
                        },
                        new
                        {
                            Id = 41,
                            Description = "Small Concrete",
                            ImgUri = "56f825c4-3d47-4707-b5ca-ef2e69461bb4",
                            Name = "Chair",
                            Price = 64.67m
                        },
                        new
                        {
                            Id = 42,
                            Description = "Small Concrete",
                            ImgUri = "d6ed37cd-7c3b-4f5a-85ab-486bead4d8db",
                            Name = "Pants",
                            Price = 43.54m
                        },
                        new
                        {
                            Id = 43,
                            Description = "Rustic Wooden",
                            ImgUri = "85d7e516-cdf3-450b-a34b-03976a208087",
                            Name = "Car",
                            Price = 13.64m
                        },
                        new
                        {
                            Id = 44,
                            Description = "Small Concrete",
                            ImgUri = "07c17165-cd25-48ea-baac-7ba93b81a69f",
                            Name = "Chair",
                            Price = 89.63m
                        },
                        new
                        {
                            Id = 45,
                            Description = "Small Wooden",
                            ImgUri = "ed6083de-3f85-4f2c-975c-e0a8388ecde1",
                            Name = "Shoes",
                            Price = 44.8m
                        },
                        new
                        {
                            Id = 46,
                            Description = "Rustic Plastic",
                            ImgUri = "44462c66-29f6-4678-9b4a-948c7ce3f205",
                            Name = "Shoes",
                            Price = 77.52m
                        },
                        new
                        {
                            Id = 47,
                            Description = "Sleek Steel",
                            ImgUri = "6b0fb5ca-7649-40b4-a090-fa7e1ca369eb",
                            Name = "Chair",
                            Price = 83.35m
                        },
                        new
                        {
                            Id = 48,
                            Description = "Rustic Steel",
                            ImgUri = "a994bf2b-073e-4852-a92c-b983cdd4965c",
                            Name = "Computer",
                            Price = 75.11m
                        },
                        new
                        {
                            Id = 49,
                            Description = "Small Steel",
                            ImgUri = "e9c5b94c-eb06-4c0c-9087-dad491612827",
                            Name = "Pants",
                            Price = 10.71m
                        },
                        new
                        {
                            Id = 50,
                            Description = "Smart Concrete",
                            ImgUri = "8c694790-e691-46a1-aa44-87164bd506e0",
                            Name = "Computer",
                            Price = 75.9m
                        },
                        new
                        {
                            Id = 51,
                            Description = "Ergonomic Granite",
                            ImgUri = "ab7f8213-994e-4d59-aabc-942e1ea5c106",
                            Name = "Shoes",
                            Price = 81.34m
                        },
                        new
                        {
                            Id = 52,
                            Description = "Rustic Steel",
                            ImgUri = "d4b8d063-5e74-410e-b5c8-e8cc22178017",
                            Name = "Car",
                            Price = 38.04m
                        },
                        new
                        {
                            Id = 53,
                            Description = "Sleek Plastic",
                            ImgUri = "4be19c6b-da4c-4746-a5c9-7a13f63c7827",
                            Name = "Computer",
                            Price = 12.2m
                        },
                        new
                        {
                            Id = 54,
                            Description = "Ergonomic Steel",
                            ImgUri = "374c5276-5b05-4033-aea8-068a08e97b95",
                            Name = "Computer",
                            Price = 66.56m
                        },
                        new
                        {
                            Id = 55,
                            Description = "Rustic Plastic",
                            ImgUri = "3923120b-55c7-474b-9ce3-8570e7dbe1a0",
                            Name = "Car",
                            Price = 52.6m
                        },
                        new
                        {
                            Id = 56,
                            Description = "Small Concrete",
                            ImgUri = "71b95d79-e086-4f9b-96fd-2f15b5b37981",
                            Name = "Pants",
                            Price = 85.94m
                        },
                        new
                        {
                            Id = 57,
                            Description = "Rustic Steel",
                            ImgUri = "b60fcde4-425a-4eb5-b3ec-c46ef3d233fe",
                            Name = "Computer",
                            Price = 40.11m
                        },
                        new
                        {
                            Id = 58,
                            Description = "Sleek Steel",
                            ImgUri = "6ee4eb7b-e950-437c-986b-86eba07b107f",
                            Name = "Shoes",
                            Price = 13.07m
                        },
                        new
                        {
                            Id = 59,
                            Description = "Rustic Steel",
                            ImgUri = "f015e04e-3a72-433a-9bb1-0ae3e715bb31",
                            Name = "Shoes",
                            Price = 59.56m
                        },
                        new
                        {
                            Id = 60,
                            Description = "Ergonomic Plastic",
                            ImgUri = "7debb192-4157-42b0-be94-986e5905e670",
                            Name = "Computer",
                            Price = 55.07m
                        },
                        new
                        {
                            Id = 61,
                            Description = "Rustic Concrete",
                            ImgUri = "b3a93a4b-83ac-47c9-bf55-ceb97365919b",
                            Name = "Computer",
                            Price = 59.27m
                        },
                        new
                        {
                            Id = 62,
                            Description = "Smart Steel",
                            ImgUri = "c9eb84c9-0a04-401d-ac12-ad8501e32dad",
                            Name = "Shoes",
                            Price = 71.56m
                        },
                        new
                        {
                            Id = 63,
                            Description = "Sleek Granite",
                            ImgUri = "3d551fec-103f-4543-a585-19bb92d9368a",
                            Name = "Pants",
                            Price = 81.1m
                        },
                        new
                        {
                            Id = 64,
                            Description = "Sleek Granite",
                            ImgUri = "0e0a5a4c-4be9-40ec-bf3f-00fbd9010ab3",
                            Name = "Car",
                            Price = 78.92m
                        },
                        new
                        {
                            Id = 65,
                            Description = "Ergonomic Steel",
                            ImgUri = "49580862-60d9-4966-b7b4-c6fdd0aca18e",
                            Name = "Shoes",
                            Price = 67.17m
                        },
                        new
                        {
                            Id = 66,
                            Description = "Ergonomic Concrete",
                            ImgUri = "3ced307a-a1e8-496b-8c87-bc33f159f32b",
                            Name = "Shoes",
                            Price = 43.89m
                        },
                        new
                        {
                            Id = 67,
                            Description = "Sleek Plastic",
                            ImgUri = "f68c2dcf-2958-438f-8b82-b394baa641a7",
                            Name = "Chair",
                            Price = 77.4m
                        },
                        new
                        {
                            Id = 68,
                            Description = "Rustic Plastic",
                            ImgUri = "1beefd1e-4021-48c6-9d87-c21f8945fa5a",
                            Name = "Car",
                            Price = 32.12m
                        },
                        new
                        {
                            Id = 69,
                            Description = "Ergonomic Granite",
                            ImgUri = "7852a067-fa94-4761-92ea-d670908fa0f6",
                            Name = "Car",
                            Price = 72.03m
                        },
                        new
                        {
                            Id = 70,
                            Description = "Smart Granite",
                            ImgUri = "97bcf54b-e0d6-48b4-b675-d534d63e568c",
                            Name = "Car",
                            Price = 57.92m
                        },
                        new
                        {
                            Id = 71,
                            Description = "Ergonomic Steel",
                            ImgUri = "fa78fc71-f350-4b1c-9644-a79d7c87c2e5",
                            Name = "Pants",
                            Price = 37.27m
                        },
                        new
                        {
                            Id = 72,
                            Description = "Smart Granite",
                            ImgUri = "76ccd403-56ad-467c-b0cd-5ac6759e63c7",
                            Name = "Chair",
                            Price = 84.82m
                        },
                        new
                        {
                            Id = 73,
                            Description = "Small Granite",
                            ImgUri = "d2b14b44-d4b1-477c-af47-1da285e2ff5d",
                            Name = "Pants",
                            Price = 51.42m
                        },
                        new
                        {
                            Id = 74,
                            Description = "Smart Granite",
                            ImgUri = "1e09d6f9-4260-42d6-a3fb-57308e5e3963",
                            Name = "Car",
                            Price = 30.57m
                        },
                        new
                        {
                            Id = 75,
                            Description = "Ergonomic Steel",
                            ImgUri = "379b931c-e44e-43b3-a46b-b4e006b0c4f8",
                            Name = "Car",
                            Price = 14.9m
                        },
                        new
                        {
                            Id = 76,
                            Description = "Sleek Concrete",
                            ImgUri = "15b72a3f-1c11-45dd-bc4a-d5d3ba2c101d",
                            Name = "Shoes",
                            Price = 85.42m
                        },
                        new
                        {
                            Id = 77,
                            Description = "Smart Concrete",
                            ImgUri = "7ddba69f-760f-429d-92ac-59b0088b9fe3",
                            Name = "Car",
                            Price = 27.15m
                        },
                        new
                        {
                            Id = 78,
                            Description = "Smart Wooden",
                            ImgUri = "104d658b-6d2a-4d75-bbc4-ebc6c4793741",
                            Name = "Computer",
                            Price = 83.54m
                        },
                        new
                        {
                            Id = 79,
                            Description = "Ergonomic Concrete",
                            ImgUri = "7853e7d9-b5a2-42b2-be07-2e7971ae4137",
                            Name = "Chair",
                            Price = 48.72m
                        },
                        new
                        {
                            Id = 80,
                            Description = "Ergonomic Steel",
                            ImgUri = "ad10a500-e2ae-4965-8cc2-b139957f6792",
                            Name = "Chair",
                            Price = 26.47m
                        },
                        new
                        {
                            Id = 81,
                            Description = "Small Plastic",
                            ImgUri = "bba21632-4515-480c-9b1e-36d07d31c85b",
                            Name = "Chair",
                            Price = 85.32m
                        },
                        new
                        {
                            Id = 82,
                            Description = "Rustic Steel",
                            ImgUri = "775392ef-8c1a-4b57-ab5b-2a7c3ade55fa",
                            Name = "Chair",
                            Price = 64.64m
                        },
                        new
                        {
                            Id = 83,
                            Description = "Smart Wooden",
                            ImgUri = "b67f4520-d743-4302-8a8d-c69343a0f3db",
                            Name = "Chair",
                            Price = 38.21m
                        },
                        new
                        {
                            Id = 84,
                            Description = "Sleek Plastic",
                            ImgUri = "5f91ec4d-cf67-453a-99c5-ae1971085233",
                            Name = "Car",
                            Price = 57.07m
                        },
                        new
                        {
                            Id = 85,
                            Description = "Smart Granite",
                            ImgUri = "b8e9dd72-0555-4ca9-8507-00950d0f9c84",
                            Name = "Computer",
                            Price = 88.8m
                        },
                        new
                        {
                            Id = 86,
                            Description = "Rustic Plastic",
                            ImgUri = "09ca49ba-aed1-4ccd-9d21-f1c7707a04e9",
                            Name = "Car",
                            Price = 19.01m
                        },
                        new
                        {
                            Id = 87,
                            Description = "Sleek Plastic",
                            ImgUri = "651efb26-8f9d-4684-9eb6-e96eb4a2d18f",
                            Name = "Shoes",
                            Price = 84.83m
                        },
                        new
                        {
                            Id = 88,
                            Description = "Sleek Steel",
                            ImgUri = "ef9985dc-3389-4072-87a3-1fd35dcaee3b",
                            Name = "Shoes",
                            Price = 23.19m
                        },
                        new
                        {
                            Id = 89,
                            Description = "Sleek Granite",
                            ImgUri = "9707e420-89cc-4885-b1cb-a975ae3841c2",
                            Name = "Pants",
                            Price = 23.85m
                        },
                        new
                        {
                            Id = 90,
                            Description = "Ergonomic Plastic",
                            ImgUri = "61654032-7a6a-4fda-8b3f-4b15e49d0d8b",
                            Name = "Shoes",
                            Price = 21.63m
                        },
                        new
                        {
                            Id = 91,
                            Description = "Rustic Steel",
                            ImgUri = "54c3963d-78dd-468a-ac58-0e982b3b6ce8",
                            Name = "Shoes",
                            Price = 66.91m
                        },
                        new
                        {
                            Id = 92,
                            Description = "Sleek Concrete",
                            ImgUri = "238e775b-1e6e-4ce1-8d3c-ef07e3242c86",
                            Name = "Car",
                            Price = 35.56m
                        },
                        new
                        {
                            Id = 93,
                            Description = "Small Steel",
                            ImgUri = "848fad6d-2158-45e2-be85-4ff1bbd18243",
                            Name = "Computer",
                            Price = 61.93m
                        },
                        new
                        {
                            Id = 94,
                            Description = "Sleek Steel",
                            ImgUri = "ee8093a2-11b8-4d20-b93b-7e45a3cc21e7",
                            Name = "Computer",
                            Price = 45.12m
                        },
                        new
                        {
                            Id = 95,
                            Description = "Sleek Steel",
                            ImgUri = "579b581d-32ba-4372-a467-6731f4ec4ebf",
                            Name = "Computer",
                            Price = 33.18m
                        },
                        new
                        {
                            Id = 96,
                            Description = "Small Granite",
                            ImgUri = "d911a120-adeb-41fc-8996-7fafbad226e5",
                            Name = "Shoes",
                            Price = 60.24m
                        },
                        new
                        {
                            Id = 97,
                            Description = "Smart Steel",
                            ImgUri = "8b96493b-b14c-486f-9ded-49360758518c",
                            Name = "Car",
                            Price = 48.29m
                        },
                        new
                        {
                            Id = 98,
                            Description = "Sleek Wooden",
                            ImgUri = "d3c09c28-7603-4df3-b744-bff1fca6447b",
                            Name = "Pants",
                            Price = 89.09m
                        },
                        new
                        {
                            Id = 99,
                            Description = "Small Concrete",
                            ImgUri = "f24a3462-e3b8-401c-b583-724ddd804045",
                            Name = "Pants",
                            Price = 17.32m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
